export const COLLECTIONS = [
  {
    id: "formationsPui",
    label: "Formations PUI",
    nav: "Formations PUI",
    accent: "prune",
    titleField: "titre",
    subtitleField: "etablissement",
    searchFields: [
      "titre",
      "objectifs",
      "etablissement",
      "contact",
      "public",
      "localisation",
    ],
    filters: ["etablissement", "niveau", "modalite", "langue", "public"],
    fields: [
      { key: "titre", label: "Titre de la formation", type: "text", required: true },
      { key: "objectifs", label: "Objectifs pédagogiques", type: "textarea" },
      { key: "etablissement", label: "Établissement", type: "text" },
      { key: "niveau", label: "Niveau", type: "text" },
      { key: "methodologie", label: "Modalités pédagogiques", type: "textarea" },
      { key: "format", label: "Format", type: "text" },
      { key: "duree", label: "Durée", type: "text" },
      { key: "modalite", label: "Modalité", type: "text" },
      { key: "public", label: "Public ciblé", type: "text" },
      { key: "pays", label: "Pays", type: "text" },
      { key: "langue", label: "Langue", type: "text" },
      { key: "cout", label: "Coût", type: "text" },
      { key: "web", label: "Site web", type: "url" },
      { key: "contact", label: "Contact", type: "text" },
      { key: "mail", label: "Mail", type: "email" },
      { key: "localisation", label: "Localisation", type: "text" },
      { key: "contributeur", label: "Contributeur", type: "text" },
    ],
  },
  {
    id: "formationsExternes",
    label: "Formations externes",
    nav: "Formations externes",
    accent: "rose",
    titleField: "titre",
    subtitleField: "etablissement",
    searchFields: ["titre", "objectifs", "etablissement", "contact"],
    filters: ["etablissement", "niveau", "langue"],
    fields: [
      { key: "titre", label: "Titre de la formation", type: "text", required: true },
      { key: "objectifs", label: "Objectifs pédagogiques", type: "textarea" },
      { key: "etablissement", label: "Établissement", type: "text" },
      { key: "niveau", label: "Niveau", type: "text" },
      { key: "methodologie", label: "Modalités pédagogiques", type: "textarea" },
      { key: "format", label: "Format", type: "text" },
      { key: "duree", label: "Durée", type: "text" },
      { key: "modalite", label: "Modalité", type: "text" },
      { key: "public", label: "Public ciblé", type: "text" },
      { key: "pays", label: "Pays", type: "text" },
      { key: "langue", label: "Langue", type: "text" },
      { key: "cout", label: "Coût", type: "text" },
      { key: "web", label: "Site web", type: "url" },
      { key: "contact", label: "Contact", type: "text" },
      { key: "mail", label: "Mail", type: "email" },
      { key: "localisation", label: "Localisation", type: "text" },
      { key: "contributeur", label: "Contributeur", type: "text" },
    ],
  },
  {
    id: "formateurs",
    label: "Formateurs",
    nav: "Formateurs",
    accent: "violet",
    titleField: "thematique",
    subtitleField: "contact",
    searchFields: ["thematique", "description", "contact", "etablissement", "fonction"],
    filters: ["origine", "rolePui", "etablissement"],
    fields: [
      { key: "thematique", label: "Thématique", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "methodologie", label: "Modalités pédagogiques", type: "textarea" },
      { key: "etablissement", label: "Établissement", type: "text" },
      { key: "fonction", label: "Fonction", type: "text" },
      { key: "origine", label: "Origine", type: "text" },
      { key: "contact", label: "Nom du contact", type: "text" },
      { key: "mail", label: "Mail", type: "email" },
      { key: "web", label: "Site web", type: "url" },
      { key: "rolePui", label: "Rôle PUI", type: "text" },
      { key: "contributeur", label: "Contributeur", type: "text" },
    ],
  },
  {
    id: "lieux",
    label: "Lieux de l'innovation",
    nav: "Lieux",
    accent: "orange",
    titleField: "nom",
    subtitleField: "etablissement",
    searchFields: ["nom", "description", "etablissement", "contact"],
    filters: ["etablissement"],
    fields: [
      { key: "nom", label: "Lieu", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "etablissement", label: "Établissement", type: "text" },
      { key: "web", label: "Lien", type: "url" },
      { key: "contact", label: "Contact", type: "text" },
      { key: "mail", label: "Mail", type: "email" },
      { key: "contributeur", label: "Contributeur", type: "text" },
    ],
  },
  {
    id: "equipements",
    label: "Équipements",
    nav: "Équipements",
    accent: "teal",
    titleField: "type",
    subtitleField: "etablissement",
    searchFields: ["type", "etablissement", "localisation", "contact"],
    filters: ["etablissement"],
    fields: [
      { key: "type", label: "Type d'équipement", type: "text", required: true },
      { key: "etablissement", label: "Établissement", type: "text" },
      { key: "localisation", label: "Localisation", type: "text" },
      { key: "web", label: "Page de référence", type: "url" },
      { key: "contact", label: "Contact", type: "text" },
      { key: "mail", label: "Mail", type: "email" },
      { key: "contributeur", label: "Contributeur", type: "text" },
    ],
  },
  {
    id: "outils",
    label: "Outils",
    nav: "Outils",
    accent: "cyan",
    titleField: "type",
    subtitleField: "description",
    searchFields: ["type", "description", "etablissement", "contact"],
    filters: ["etablissement"],
    fields: [
      { key: "type", label: "Type", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "etablissement", label: "Établissement", type: "text" },
      { key: "web", label: "Lien", type: "url" },
      { key: "contact", label: "Contact", type: "text" },
      { key: "mail", label: "Mail", type: "email" },
      { key: "fonction", label: "Fonction", type: "text" },
      { key: "contributeur", label: "Contributeur", type: "text" },
    ],
  },
  {
    id: "bibliographie",
    label: "Bibliographie",
    nav: "Bibliographie",
    accent: "slate",
    titleField: "titre",
    subtitleField: "auteur",
    searchFields: ["titre", "auteur", "notes", "localisation"],
    filters: ["type", "annee"],
    fields: [
      { key: "titre", label: "Titre", type: "text", required: true },
      { key: "auteur", label: "Auteur", type: "text" },
      { key: "annee", label: "Année", type: "text" },
      { key: "type", label: "Type", type: "text" },
      { key: "web", label: "Lien de référence", type: "url" },
      { key: "isbn", label: "ISBN", type: "text" },
      { key: "notes", label: "Notes", type: "textarea" },
      { key: "localisation", label: "Localisation", type: "text" },
      { key: "contributeur", label: "Contributeur", type: "text" },
    ],
  },
  {
    id: "financements",
    label: "Financements",
    nav: "Financements",
    accent: "prune",
    titleField: "organisme",
    subtitleField: "niveau",
    searchFields: ["organisme", "niveau", "lien"],
    filters: ["niveau"],
    fields: [
      { key: "niveau", label: "Niveau", type: "text" },
      { key: "organisme", label: "Organisme / appel à projets", type: "text", required: true },
      { key: "lien", label: "Lien", type: "url" },
    ],
  },
  {
    id: "seFormerAvenir",
    label: "Se former pour l'avenir",
    nav: "Se former",
    accent: "rose",
    titleField: "programme",
    subtitleField: "action",
    searchFields: ["action", "programme", "contact"],
    filters: ["rythme"],
    fields: [
      { key: "action", label: "Action", type: "text" },
      { key: "programme", label: "Programme", type: "text", required: true },
      { key: "contact", label: "Contact", type: "text" },
      { key: "lien", label: "Lien", type: "url" },
      { key: "rythme", label: "Rythme", type: "text" },
    ],
  },
  {
    id: "etablissementsValo",
    label: "Établissements valorisation",
    nav: "Établissements",
    accent: "violet",
    titleField: "etablissement",
    subtitleField: "contactValo",
    searchFields: ["etablissement", "web", "contactValo"],
    filters: [],
    fields: [
      { key: "etablissement", label: "Établissement", type: "text", required: true },
      { key: "web", label: "Site web", type: "url" },
      { key: "contactValo", label: "Contact cellule valo", type: "text" },
    ],
  },
];

export const COLLECTION_BY_ID = Object.fromEntries(
  COLLECTIONS.map((c) => [c.id, c])
);

export const PARCOURS = [
  {
    id: "former",
    kicker: "01",
    label: "Se former",
    lead: "Parcours, modules et programmes pour enseigner et apprendre l’innovation.",
    collections: ["formationsPui", "formationsExternes", "seFormerAvenir"],
  },
  {
    id: "faire",
    kicker: "02",
    label: "Concevoir et prototyper",
    lead: "Lieux, équipements et personnes ressources pour passer de l’idée au démonstrateur.",
    collections: ["lieux", "equipements", "formateurs"],
  },
  {
    id: "appuyer",
    kicker: "03",
    label: "S’appuyer",
    lead: "Outils, références, financements et cellules de valorisation du périmètre.",
    collections: ["outils", "bibliographie", "financements", "etablissementsValo"],
  },
];

export const THEMES = [
  { id: "pi", label: "Propriété intellectuelle", keys: ["propriete intellectuelle", " pi", "brevet", "inpi", "contrats"] },
  { id: "entrepreneuriat", label: "Entrepreneuriat", keys: ["entrepreneur", "startup", "start-up", "start up", "pepite", "incub"] },
  { id: "deeptech", label: "Deeptech", keys: ["deeptech", "deep tech"] },
  { id: "design", label: "Design", keys: ["design", "conception"] },
  { id: "valorisation", label: "Valorisation", keys: ["valoris", "transfert", "satt"] },
  { id: "ia", label: "Intelligence artificielle", keys: ["intelligence artificielle", "ia ", "ai ", "ia act"] },
  { id: "pedagogie", label: "Pédagogie et jeu", keys: ["ludo", "jeu", "pedagog", "mooc"] },
  { id: "financement", label: "Financement", keys: ["financement", "anr", "horizon", "bpi", "cifre", "appel"] },
];
